-- Create the orders table
create table orders (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  customer_name text,
  customer_phone text,
  customer_email text,
  status text default 'new',
  total_price numeric,
  configuration jsonb,
  delivery_type text,
  payment_method text
);

-- Enable Row Level Security
alter table orders enable row level security;

-- Create a policy to allow ANYONE to insert/update/select/delete (For public admin without auth as requested)
-- WARNING: This is unsecure and should be restricted in production!
create policy "Allow All Access" on orders for all using (true) with check (true);
